/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2024-04-25 11:40:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import com.mobilestore.model.*;
import com.mobilestore.dao.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/components/message.jsp", Long.valueOf(1711356945830L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1711732011469L));
    _jspx_dependants.put("/components/bootstrap_css_js.jsp", Long.valueOf(1711357153032L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.mobilestore.dao");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.mobilestore.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login for Mobile Mart</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\"> \r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/login.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("   ");

     User user=(User)session.getAttribute("active-user"); 
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

         BrandDaoImp bdao=new BrandDaoImp();
         List<Brand> cl=bdao.getAllBrand();   
     
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light custom-bg fixed-top\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("    ");

         if(user!=null) {
     
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("      <div class=\"dropdown\">\r\n");
      out.write("      <div style=\"width:36px;height:36px;background-image:radial-gradient(circle,black 3.6px,transparent 4.6px); background-size:100% 33.33%;\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"></div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("         <div class=\"dropdown-item\" data-toggle=\"modal\" data-target=\"#showprofilemodal\"><b>My Profile</b></div>\r\n");
      out.write("         <div class=\"dropdown-item\" data-toggle=\"modal\" data-target=\".changepasswordmodal\"><b>Change Password</b></div>\r\n");
      out.write("         <div class=\"dropdown-item\" data-toggle=\"modal\" data-target=\".logout-modal\"><b>Logout</b></div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          \r\n");
      out.write("      ");
   }  
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <h3 style=\"margin-left:15px;\">  <a class=\"navbar-brand\" href=\"index.jsp\"> <i><b>Mobile Mart</b></i></a> </h3>\r\n");
      out.write("  \r\n");
      out.write("         <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("           <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("         </button>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("           <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("           \r\n");
      out.write("      ");

         if(user!=null)  {
        	 
        	 String userType=user.getUserType();
        	 if(userType.equals("admin")) {
      
      out.write("\r\n");
      out.write("         <li class=\"nav-item active\">\r\n");
      out.write("             <a class=\"nav-link\" href=\"admin.jsp\"><b>Admin Page</b> <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("         </li>\r\n");
      out.write("      ");

        	 }
         }
      
      out.write("\r\n");
      out.write("           \r\n");
      out.write("  \r\n");
      out.write("         <li class=\"nav-item active dropdown\">\r\n");
      out.write("         <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <b> Brands</b>  </a>\r\n");
      out.write("    \r\n");
      out.write("         <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("         <a class=\"dropdown-item\" href=\"index.jsp?category=0\">All</a> \r\n");
      out.write("        \r\n");
      out.write("       ");

            for(Brand c: cl)  {    	
               
      out.write(" \r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"index.jsp?category=");
      out.print(c.getBrandId() );
      out.write('"');
      out.write('>');
      out.print(c.getBrandTitle() );
      out.write("</a>     \r\n");
      out.write("               ");

                    }
               
      out.write("\r\n");
      out.write("          \r\n");
      out.write("           </div> \r\n");
      out.write("           </li>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("           <li class=\"nav-item active dropdown\">\r\n");
      out.write("             <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("             <b>Filter</b> </a>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("             <a class=\"dropdown-item\" href=\"index.jsp?filter=10000\">&#8377;10000</a>\r\n");
      out.write("             <a class=\"dropdown-item\" href=\"index.jsp?filter=20000\"> &#8377;20000</a>\r\n");
      out.write("             <a class=\"dropdown-item\" href=\"index.jsp?filter=30000\"> &#8377;30000</a>\r\n");
      out.write("             <a class=\"dropdown-item\" href=\"index.jsp?filter=50000\"> &#8377;50000</a>\r\n");
      out.write("             <a class=\"dropdown-item\" href=\"index.jsp?filter=100000\"> Over &#8377;100000</a>\r\n");
      out.write("            </div>\r\n");
      out.write("         \r\n");
      out.write("           </li>\r\n");
      out.write("      \r\n");
      out.write("           <li class=\"nav-item active ml-2\" data-toggle=\"modal\" data-target=\".contactusmodal\">\r\n");
      out.write("             <div class=\"nav-link\" ><b>Contact us</b></div>\r\n");
      out.write("           </li>\r\n");
      out.write("           \r\n");
      out.write("        </ul>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("          <form class=\"form-inline my-2 my-lg-0\"  method=\"post\" action=\"ProductOperation\" id=\"searchform\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"searchProduct\" >\r\n");
      out.write("            <input class=\"form-control mr-md-2\" type=\"text\" placeholder=\"Search product\" aria-label=\"Search\" size=\"80\" name=\"search\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-light\" style=\"color:black\"><b>Search</b></button>\r\n");
      out.write("          </form>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("      ");

        if(user!=null)
        {    	  
      
      out.write("\r\n");
      out.write("  \r\n");
      out.write("      <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      ");

         if(user.getUserType().equals("user"))  {
             
       
      out.write("\r\n");
      out.write("          \r\n");
      out.write("             \r\n");
      out.write("               <li class=\"nav-item active\" data-toggle=\"modal\" data-target=\"#showmycartmodal\">\r\n");
      out.write("               <div class=\"nav-link\"><img src=\"images/cart.png\" style=\"width:23px;\" alt=\"img\">(");
      out.print(new CartDaoImp().totalCartByUserId(user.getUserId()) );
      out.write(")</div>\r\n");
      out.write("               </li> \r\n");
      out.write("                     \r\n");
      out.write("               <li class=\"nav-item active\" data-toggle=\"modal\" data-target=\"#showmyordermodal\">\r\n");
      out.write("               <a class=\"nav-link\" href=\"#\"><b>My Orders</b></a>\r\n");
      out.write("               </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("              \r\n");
      out.write("              ");
   }   
      out.write("\r\n");
      out.write("              \r\n");
      out.write("       ");
  }
    
        else
          {
        
      out.write("\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("        \r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"register.jsp\" ><b>Register</b></a>\r\n");
      out.write("            </li>  \r\n");
      out.write("      \r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"login.jsp\"><b>Login</b></a>\r\n");
      out.write("            </li>\r\n");
      out.write("                \r\n");
      out.write("           </ul>\r\n");
      out.write("        ");
   }   
      out.write(" \r\n");
      out.write("       \r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write(" </nav>\r\n");
      out.write(" \r\n");
      out.write(" <!-- show profile modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"showprofilemodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY PROFILE</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("         <form >\r\n");
      out.write("         \r\n");
      out.write("            <div class=\"container text-center\">\r\n");
      out.write("                <img style=\"max-width:200px\" class=\"img-fluid rounded-circle\" src=\"userProfilePic/");
if(user!=null){ 
      out.print(user.getUserPic() );
} 
      out.write("\" alt=\"users_pic\" >\r\n");
      out.write("            </div> \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-row mt-3\">\r\n");
      out.write("        \r\n");
      out.write("             <div class=\"form-group col-md-4\">\r\n");
      out.write("             <label for=\"inputEmail4\">Name</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"inputEmail4\" value=\"");
if(user!=null){ 
      out.print(user.getUserName() );
} 
      out.write("\" readonly>\r\n");
      out.write("             </div>\r\n");
      out.write("           \r\n");
      out.write("             <div class=\"form-group col-md-4\">\r\n");
      out.write("             <label for=\"inputPassword4\">Email</label>\r\n");
      out.write("             <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\r\n");
      out.write("             </div>\r\n");
      out.write("    \r\n");
      out.write("             <div class=\"form-group col-md-4\">\r\n");
      out.write("             <label for=\"inputPassword4\">Phone</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserPhone() );
} 
      out.write("\" readonly>\r\n");
      out.write("             </div>\r\n");
      out.write("    \r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("            <label for=\"inputAddress\">Address</label>\r\n");
      out.write("            <textarea class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\" rows=\"3\" readonly>");
if(user!=null){ 
      out.print(user.getUserAddress() );
} 
      out.write("</textarea>\r\n");
      out.write("            </div>\r\n");
      out.write(" \r\n");
      out.write("            <div class=\"container text-center\">\r\n");
      out.write("            <button type=\"button\" class=\"btn custom-bg text-light\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("            </div> \r\n");
      out.write("              \r\n");
      out.write("         </form>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("<!-- show my cart modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"showmycartmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY CART</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("     ");

      if(user!=null)
      {
    	  List<Cart> l=new CartDaoImp().getCartByUserId(user.getUserId());
    	 
     
      out.write("\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        \r\n");
      out.write("        ");

            if(l.isEmpty())
            {
        
      out.write("\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("        <h1>CART IS EMPTY!!</h1>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            }
        
            else
            {
            	
            	
        
      out.write("\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("          <table class=\"table\">\r\n");
      out.write("  <thead class=\"custom-bg text-white\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">Product Image</th>\r\n");
      out.write("      <th scope=\"col\">Title</th>    \r\n");
      out.write("      <th scope=\"col\">Description</th>\r\n");
      out.write("      <th scope=\"col\">Brand</th>\r\n");
      out.write("      <th scope=\"col\">Quantity</th>\r\n");
      out.write("      <th scope=\"col\">Price</th>\r\n");
      out.write("      <th scope=\"col\">Action</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  <tbody>\r\n");
      out.write("   ");

      CartDaoImp ctdao=new CartDaoImp();
      
   
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   ");

      for(Cart c:l)
      {
    	  int productId=c.getProductId();
    	  Product p=new ProductDaoImp().getProductById(productId);
   
      out.write("\r\n");
      out.write("    <tr class=\"text-left\">\r\n");
      out.write("      <td><img style=\"max-height:100px;max-width:120px;width:auto;\" class=\"img-fluid mx-auto d-block\" src=\"productImages/");
      out.print(p.getProductPhoto() );
      out.write("\" alt=\"users_pic\" ></td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductTitle() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(p.getProductDescription() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(new BrandDaoImp().getBrandNameById(p.getBrandId()) );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(c.getQuantity() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(c.getPrice() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\"><a href=\"CartServlet?cartId=");
      out.print(c.getCartId());
      out.write("&action=delete\"><button type=\"button\" class=\"btn btn-danger\">Remove</button></a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

      }
    
      out.write("\r\n");
      out.write("  </tbody>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-left\">\r\n");
      out.write("    <p style=\"font-size:25px;\"><b>Total Price :&#8377;");
      out.print(new CartDaoImp().totalPriceFromCart(user.getUserId()) );
      out.write("/- </b></p> \r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("      <form action=\"authorize_payment\" method=\"post\">\r\n");
      out.write("          <input type=\"hidden\" name=\"userId\" value=\"");
      out.print(user.getUserId());
      out.write("\">\r\n");
      out.write("          <input type=\"submit\" class=\"btn custom-bg text-light ml-5\" value=\"Order\">\r\n");
      out.write("   </form>\r\n");
      out.write("   <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("       ");

            }
       
      out.write("\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("  ");

           
      }
  
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("<!-- show my order modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"showmyordermodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg modal-size\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >MY ORDERS</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("     ");

      if(user!=null)
      {
    	  List<Order> l=new OrderDaoImp().getOrderByUserId(user.getUserId());
    	 
     
      out.write("\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        \r\n");
      out.write("        ");

            if(l.isEmpty())
            {
        
      out.write("\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("        <h1>NO ORDERS MADE BY YOU !!</h1>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            }
        
            else
            {
            	
            	
        
      out.write("\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("          <table class=\"table\">\r\n");
      out.write("  <thead class=\"custom-bg text-white\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">Product Image</th>\r\n");
      out.write("      <th scope=\"col\">Product Title</th> \r\n");
      out.write("      <th scope=\"col\">Product Description</th>\r\n");
      out.write("      <th scope=\"col\">Product Brand</th>   \r\n");
      out.write("      <th scope=\"col\">Quantity</th>\r\n");
      out.write("      <th scope=\"col\">Price</th>\r\n");
      out.write("      <th scope=\"col\">Ordered Date</th>\r\n");
      out.write("      <th scope=\"col\">Delivery Date</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  <tbody>\r\n");
      out.write("   ");

      OrderDaoImp odao=new OrderDaoImp();
      
   
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   ");

      for(Order o:l)
      {
    	  int productId=o.getProdctId();
    	  Product p=new ProductDaoImp().getProductById(productId);
   
      out.write("\r\n");
      out.write("    <tr class=\"text-left\">\r\n");
      out.write("      <td><img style=\"max-height:100px;max-width:70px;width:auto;\" class=\"img-fluid mx-auto d-block\" src=\"productImages/");
      out.print(p.getProductPhoto() );
      out.write("\" alt=\"users_pic\" ></td>\r\n");
      out.write("      <td class=\"text-start\">");
      out.print(p.getProductTitle() );
      out.write("</td>\r\n");
      out.write("      <td style=\"text-align:left;\">");
      out.print(p.getProductDescription() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(new BrandDaoImp().getBrandNameById(p.getBrandId()) );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getQuantity() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getPrice() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
      out.print(o.getOrderesDate() );
      out.write("</td>\r\n");
      out.write("      <td class=\"mid-align\">");
if(o.getDeliveryDate().equals("0")){ 
      out.write("<span style=\"color:red;\"> ");
      out.print("processing..");
      out.write("</span>    ");
} else { 
      out.write(' ');
      out.print(o.getDeliveryDate() );
} 
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

      }
    
      out.write("\r\n");
      out.write("  </tbody>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-left\">\r\n");
      out.write("    <p style=\"font-size:25px;\"><b>Total Price :&#8377;");
      out.print(new OrderDaoImp().totalOrderPrice(user.getUserId()) );
      out.write("/- </b></p> \r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"button\" class=\"btn btn-secondary ml-5\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\r\n");
      out.write("       ");

            }
       
      out.write("\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("  ");

           
      }
  
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("<!-- Logout modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade logout-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Log Out</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body text-center\">\r\n");
      out.write("            <h5>Do you want to logout?</h5>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"text-center\">\r\n");
      out.write("            <a href=\"LoginServlet\"><button type=\"button\" class=\"btn custom-bg text-white\">Yes</button></a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary ml-5\" data-dismiss=\"modal\">No</button>\r\n");
      out.write("          </div> \r\n");
      out.write("     </div>     \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- *********** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Contact us modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade contactusmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("       <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Contact Us</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div> \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("        <p style=\"font-size:23px;\">\r\n");
      out.write("            <b>\r\n");
      out.write("                <img src=\"images/phonee.png\" style=\"width:27px;\" alt=\"img\">+91 8235937186<br>\r\n");
      out.write("                <img src=\"images/emaill.png\" style=\"width:29px;\" alt=\"img\">nnr9798@gmail.com\r\n");
      out.write("            </b>\r\n");
      out.write("        </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("       <div class=\"text-center\">\r\n");
      out.write("        <button type=\"button\" class=\"btn custom-bg text-white\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("       </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ********** -->\r\n");
      out.write("\r\n");
      out.write("<!-- change password modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade changepasswordmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Change Password</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("          <form action=\"login\" method=\"post\">\r\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"changePassword\">\r\n");
      out.write("         \r\n");
      out.write("  <div class=\"form\">\r\n");
      out.write(" \r\n");
      out.write("    <div class=\"form-group \">\r\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"inputPassword4\" value=\"");
if(user!=null){ 
      out.print(user.getUserEmail() );
} 
      out.write("\" readonly>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"inputPassword4\">Password</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\" >\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"inputPassword4\">Confirm Password</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"cpass\" name=\"cpass\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"container text-center\">\r\n");
      out.write("       \r\n");
      out.write("       <input type=\"submit\" class=\"btn custom-bg text-light\" value=\"Change\">\r\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                      \r\n");
      out.write("  </div>   \r\n");
      out.write("</form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("             \r\n");
      out.write("     <div class=\"container\">\r\n");
      out.write("      ");

    String message=(String)session.getAttribute("message");
    if(message!=null)
    {
    	//out.print(message);

      out.write("\r\n");
      out.write("    <div class=\"alert alert-success alert-dismissible fade show text-center\" role=\"alert\">\r\n");
      out.write("        <strong>");
      out.print(message );
      out.write("</strong>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
      out.write("        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("   </div>\r\n");
    		
    	session.removeAttribute("message");
    }

      out.write("\r\n");
      out.write("      <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"title\"><span>Login Form</span></div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("        \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <i class=\"fas fa-user\"></i>\r\n");
      out.write("            <input type=\"email\" id=\"exampleInputEmail1\" name=\"email\" placeholder=\"Enter Email\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <i class=\"fas fa-lock\"></i>\r\n");
      out.write("            <input type=\"password\" id=\"exampleInputPassword1\" name=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"pass\" data-toggle=\"modal\" data-target=\".forgetpasswordmodal\"><a>Forget password</a> </div>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          <div class=\"row button\">\r\n");
      out.write("            <input type=\"submit\" value=\"Login\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"signup-link\">Not a member? <a href=\"register.jsp\">Signup now</a></div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>          \r\n");
      out.write("                \r\n");
      out.write("  \r\n");
      out.write("  <!-- forget password modal -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade forgetpasswordmodal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header custom-bg text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\" >Forget Password</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("          <form action=\"login\" method=\"post\">\r\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"forgetPassword\">\r\n");
      out.write("         \r\n");
      out.write("  <div class=\"form\">\r\n");
      out.write(" \r\n");
      out.write("    <div class=\"form-group \">\r\n");
      out.write("      <label for=\"inputPassword4\">Email</label>\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group \">\r\n");
      out.write("      <label for=\"inputPassword4\">Phone</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"inputPassword4\">Password</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"inputPassword4\">Confirm Password</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"cpass\" name=\"cpass\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"container text-center\">\r\n");
      out.write("       \r\n");
      out.write("       <input type=\"submit\" class=\"btn custom-bg text-light\" value=\"Change\">\r\n");
      out.write("       \r\n");
      out.write("       <button type=\"button\" class=\"btn custom-bg text-light ml-5\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                      \r\n");
      out.write("  </div>   \r\n");
      out.write("</form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
